package tocadiscos

import (
	"fmt"
	"math"
)

type Nota float64

const (
	A4Frequency = 440.0 // Frequency of A4 (reference note)
)

// NoteFrequency returns the frequency of a note n semitones away from A4.
func NoteFrequency(n int) Nota {
	return Nota(A4Frequency * math.Pow(2, float64(n)/12))
}

func (n Nota) Frequency() string {
	return fmt.Sprintf("%.2f Hz", n)
}

// Define notes using NoteFrequency function
var (
	C8           Nota = NoteFrequency(39)
	B7           Nota = NoteFrequency(38)
	A7_SOSTENIDO Nota = NoteFrequency(37)
	A7           Nota = NoteFrequency(36)
	G7_SOSTENIDO Nota = NoteFrequency(35)
	G7           Nota = NoteFrequency(34)
	F7_SOSTENIDO Nota = NoteFrequency(33)
	F7           Nota = NoteFrequency(32)
	E7           Nota = NoteFrequency(31)
	D7_SOSTENIDO Nota = NoteFrequency(30)
	D7           Nota = NoteFrequency(29)
	C7_SOSTENIDO Nota = NoteFrequency(28)
	C7           Nota = NoteFrequency(27)
	B6           Nota = NoteFrequency(26)
	A6_SOSTENIDO Nota = NoteFrequency(25)
	A6           Nota = NoteFrequency(24)
	G6_SOSTENIDO Nota = NoteFrequency(23)
	G6           Nota = NoteFrequency(22)
	F6_SOSTENIDO Nota = NoteFrequency(21)
	F6           Nota = NoteFrequency(20)
	E6           Nota = NoteFrequency(19)
	D6_SOSTENIDO Nota = NoteFrequency(18)
	D6           Nota = NoteFrequency(17)
	C6_SOSTENIDO Nota = NoteFrequency(16)
	C6           Nota = NoteFrequency(15)
	B5           Nota = NoteFrequency(14)
	A5_SOSTENIDO Nota = NoteFrequency(13)
	A5           Nota = NoteFrequency(12)
	G5_SOSTENIDO Nota = NoteFrequency(11)
	G5           Nota = NoteFrequency(10)
	F5_SOSTENIDO Nota = NoteFrequency(9)
	F5           Nota = NoteFrequency(8)
	E5           Nota = NoteFrequency(7)
	D5_SOSTENIDO Nota = NoteFrequency(6)
	D5           Nota = NoteFrequency(5)
	C5_SOSTENIDO Nota = NoteFrequency(4)
	C5           Nota = NoteFrequency(3)
	B4           Nota = NoteFrequency(2)
	A4_SOSTENIDO Nota = NoteFrequency(1)
	A4           Nota = NoteFrequency(0)
	G4_SOSTENIDO Nota = NoteFrequency(-1)
	G4           Nota = NoteFrequency(-2)
	F4_SOSTENIDO Nota = NoteFrequency(-3)
	F4           Nota = NoteFrequency(-4)
	E4           Nota = NoteFrequency(-5)
	D4_SOSTENIDO Nota = NoteFrequency(-6)
	D4           Nota = NoteFrequency(-7)
	C4_SOSTENIDO Nota = NoteFrequency(-8)
	C4           Nota = NoteFrequency(-9)
	B3           Nota = NoteFrequency(-10)
	A3_SOSTENIDO Nota = NoteFrequency(-11)
	A3           Nota = NoteFrequency(-12)
	G3_SOSTENIDO Nota = NoteFrequency(-13)
	G3           Nota = NoteFrequency(-14)
	F3_SOSTENIDO Nota = NoteFrequency(-15)
	F3           Nota = NoteFrequency(-16)
	E3           Nota = NoteFrequency(-17)
	D3_SOSTENIDO Nota = NoteFrequency(-18)
	D3           Nota = NoteFrequency(-19)
	C3_SOSTENIDO Nota = NoteFrequency(-20)
	C3           Nota = NoteFrequency(-21)
	B2           Nota = NoteFrequency(-22)
	A2_SOSTENIDO Nota = NoteFrequency(-23)
	A2           Nota = NoteFrequency(-24)
	G2_SOSTENIDO Nota = NoteFrequency(-25)
	G2           Nota = NoteFrequency(-26)
	F2_SOSTENIDO Nota = NoteFrequency(-27)
	F2           Nota = NoteFrequency(-28)
	E2           Nota = NoteFrequency(-29)
	D2_SOSTENIDO Nota = NoteFrequency(-30)
	D2           Nota = NoteFrequency(-31)
	C2_SOSTENIDO Nota = NoteFrequency(-32)
	C2           Nota = NoteFrequency(-33)
	B1           Nota = NoteFrequency(-34)
	A1_SOSTENIDO Nota = NoteFrequency(-35)
	A1           Nota = NoteFrequency(-36)
	G1_SOSTENIDO Nota = NoteFrequency(-37)
	G1           Nota = NoteFrequency(-38)
	F1_SOSTENIDO Nota = NoteFrequency(-39)
	F1           Nota = NoteFrequency(-40)
	E1           Nota = NoteFrequency(-41)
	D1_SOSTENIDO Nota = NoteFrequency(-42)
	D1           Nota = NoteFrequency(-43)
	C1_SOSTENIDO Nota = NoteFrequency(-44)
	C1           Nota = NoteFrequency(-45)
	B0           Nota = NoteFrequency(-46)
	A0_SOSTENIDO Nota = NoteFrequency(-47)
	A0           Nota = NoteFrequency(-48)
)
